// Define the Technologie enum with keys and values
export enum Technologie {
    HTML = 'HTML',
    CSS = 'CSS',
    JavaScript = 'JavaScript',
    ReactJS = 'ReactJS',
    Angular = 'Angular',
    VueJS = 'VueJS',
    Bootstrap = 'Bootstrap',
    Sass = 'Sass',
    jQuery = 'jQuery',
    TypeScript = 'TypeScript',
    EmberJS = 'EmberJS',
    BackboneJS = 'BackboneJS',
    WebAssembly = 'WebAssembly',
    GraphQL = 'GraphQL',
    HandlebarsJS = 'HandlebarsJS',
    Pug = 'Pug',
    NodeJS = 'NodeJS',
    Django = 'Django',
    Flask = 'Flask',
    RubyOnRails = 'RubyOnRails',
    ExpressJS = 'ExpressJS',
    ASPNET = 'ASPNET',
    SpringBoot = 'SpringBoot',
    Laravel = 'Laravel',
    Symfony = 'Symfony',
    FastAPI = 'FastAPI',
    NestJS = 'NestJS',
    Gin = 'Gin',
    Echo = 'Echo',
    KoaJS = 'KoaJS',
    MeteorJS = 'MeteorJS',
    MySQL = 'MySQL',
    PostgreSQL = 'PostgreSQL',
    MongoDB = 'MongoDB',
    SQLite = 'SQLite',
    MicrosoftSQLServer = 'MicrosoftSQLServer',
    OracleDatabase = 'OracleDatabase',
    Redis = 'Redis',
    FirebaseRealtimeDatabase = 'FirebaseRealtimeDatabase',
    AmazonDynamoDB = 'AmazonDynamoDB',
    Couchbase = 'Couchbase'
}


